[package]
name = "rust-studies"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
rand = "*"

[[bin]]
name = "multithread_cli"
path = "src/studies/multithread_cli.rs"